# config/active_agent.yml
openai: &openai
  service: "OpenAI"
  access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "lm-studio") %> # ダミー可
  host: <%= ENV.fetch("OPENAI_HOST", "http://192.168.10.10:1234/v1") %>  # ★ ここが重要

development:
  openai:
    <<: *openai
    model: <%= ENV.fetch("OPENAI_MODEL", ENV.fetch("OPENAI_CHAT_MODEL", "openai/gpt-oss-20b")) %>
    temperature: 0.7

test:
  openai:
    <<: *openai
    model: "gpt-4o-mini" # ここはダミーでもOK（使わなければ関係なし）
